# Generated by Django 2.2.3 on 2019-07-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regioes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('regiao', models.CharField(choices=[('zl', 'Zona Leste'), ('zn', 'Zona Norte'), ('zo', 'Zona Oeste'), ('zs', 'Zona Sul'), ('ct', 'Centro'), ('ot', 'Outra Região')], max_length=200)),
                ('salario', models.CharField(max_length=50)),
                ('qtd_vaga', models.TextField()),
                ('Descricao_vaga', models.TextField()),
            ],
        ),
    ]
