# Generated by Django 2.2.3 on 2019-07-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190704_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuaria', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=14)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='empresas',
            name='qtd_vaga',
            field=models.CharField(max_length=2),
        ),
    ]
