# Generated by Django 2.2.3 on 2019-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190710_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuaria',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuaria',
            name='senha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuaria',
            name='sobrenome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuaria',
            name='telefone',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='usuaria',
            name='usuaria',
            field=models.CharField(default='', max_length=20),
        ),
    ]
