# Generated by Django 2.2.3 on 2019-07-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190710_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
