# Generated by Django 2.2.3 on 2019-07-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_seguranca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguranca',
        ),
    ]
