# Generated by Django 2.2.3 on 2019-07-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_seguranca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuaria',
            old_name='usuaria',
            new_name='usuária',
        ),
    ]
