# Generated by Django 2.2.3 on 2019-07-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190715_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuaria',
            old_name='usuária',
            new_name='usuaria',
        ),
    ]
